###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Celeste"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Celeste",
    "number": "549-999"
}